### ISSUE TITLE
使用0.2.0后报错

### ISSUE THREAD

**Issue by grand3654331** [fzxiao233/Vtb_Record#59]
具体如下：
![报错](https://user-images.githubusercontent.com/54953020/88400674-41a46680-cdfb-11ea-8ac1-48249869446b.png)
![报错配置](https://user-images.githubusercontent.com/54953020/88400705-4a953800-cdfb-11ea-9524-4699ef3dc9b5.png)

**Comment by fzxiao233** [comment]
感谢反馈和修复
