### ISSUE TITLE
youtube cannot find ytInitialGuideData

### ISSUE THREAD

**Issue by kudmi** [fzxiao233/Vtb_Record#67]
請問出現了
WARN[0000]youtube.go:244 IsLiving() Failed to poll from youtube                   error="youtube cannot find ytInitialGuideData"
是甚麼問題呢?

![擷取](https://user-images.githubusercontent.com/45892692/95679694-7e6c4680-0c0f-11eb-9fe8-9b7cef866754.JPG)

**Comment by fzxiao233** [comment]
#68
