### ISSUE TITLE
报错：Invalid data found when processing input

### ISSUE THREAD

**Issue by Akegarasu** [fzxiao233/Vtb_Record#73]
## 环境：streamlink、ffmpeg均安装
在文件夹中无限产生0kb的文件
配置文件：
`{
  "LogFile": "Record.log",
  "LogFileSize": 20,
  "LogLevel": "debug",
  "RLogLevel": "debug",
  "PprofHost": "0.0.0.0:49314",
  "RedisHost": "127.0.0.1:6379",
  "CriticalCheckSec": 60,
  "NormalCheckSec": 60,
  "ExpressPort": 3000,
  "DownloadQuality": "best",
  "DownloadDir": ["/www/wwwroot/rec.qiuye.ink/rec/down"],
  "UploadDir": "/www/wwwroot/rec.qiuye.ink/rec/up",
  "EnableTS2MP4": true,
  "Module": [
    {
      "Name": "Youtube",
      "Enable": true,
      "Users": [
        {
          "TargetId": "UC1DCedRgGHBdm81E1llLhOQ",
          "Name": "usadapekora",
          "NeedDownload": true,
          "StreamLinkArgs": ["--http-cookies", "替换过的cookies"]
        }
      ],
      "HttpHeaders": {
        "Cookie": "YOUTUBE_COOKIE_FOR_MONITOR"
      }
    }
  ]
}`
## pm2的log文件 
`5|vtb_rec  | ��こら】_1604417121.ts|/www/wwwroot/rec.qiuye.ink/rec/down/usadapekora/【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】_1604417122.ts|/www/wwwroot/rec.qiuye.ink/rec/down/usadapekora/【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】_1604417122.ts|/www/wwwroot/rec.qiuye.ink/rec/down/usadapekora/【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】_1604417123.ts|/www/wwwroot/rec.qiuye.ink/rec/down/usadapekora/【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】_1604417123.ts|/www/wwwroot/rec.qiuye.ink/rec/down/usadapekora/【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】_1604417145.ts|/www/wwwroot/rec.qiuye.ink/rec/down/usadapekora/【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】_1604417145.ts|' for reading  title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"
5|vtb_rec  | INFO[0025]shellSupport.go:41 func2() concat:/www/wwwroot/rec.qiuye.ink/rec/down/usadapekora/【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】_1604417121.ts|/www/wwwroot/rec.qiuye.ink/rec/down/usadapekora/【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】_1604417122.ts|/www/wwwroot/rec.qiuye.ink/rec/down/usadapekora/【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】_1604417122.ts|/www/wwwroot/rec.qiuye.ink/rec/down/usadapekora/【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】_1604417123.ts|/www/wwwroot/rec.qiuye.ink/rec/down/usadapekora/【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】_1604417123.ts|/www/wwwroot/rec.qiuye.ink/rec/down/usadapekora/【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】_1604417145.ts|/www/wwwroot/rec.qiuye.ink/rec/down/usadapekora/【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】_1604417145.ts|: Invalid data found when processing input  title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"
5|vtb_rec  | WARN[0025]videoProcesser.go:331 mergeVideo() /www/wwwroot/rec.qiuye.ink/rec/up/usadapekora/【2020-11-03】【23:25:21】【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】_merged_1604417145.mp4 the video file don't exist  title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora`

**Comment by Akegarasu** [comment]
附加一段
`5|vtb_rec  | WARN[0183]videoProcesser.go:331 mergeVideo() /www/wwwroot/rec.qiuye.ink/rec/up/usadapekora/【2020-11-03】【23:26:21】【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】_merged_1604417303.mp4 the video file don't exist  title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"
5|vtb_rec  | WARN[0240]prof.go:22 PrintMemUsage() Alloc = 2 MiB	TotalAlloc = 92 MiB	Sys = 68 MiB	Goroutines = 19	NumGC = 171  prof=true
5|vtb_rec  | [2020-11-03T23:29:34+08:00] Unable to send logs to fluentd, reconnecting...
5|vtb_rec  | WARN[0300]prof.go:22 PrintMemUsage() Alloc = 2 MiB	TotalAlloc = 92 MiB	Sys = 68 MiB	Goroutines = 17	NumGC = 211  prof=true
5|vtb_rec  | INFO[0300]main.go:116 arrangeTask() current living []                            
5|vtb_rec  | INFO[0300]videoProcesser.go:61 StartProcessVideo() is living. start to process                   title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"
5|vtb_rec  | INFO[0300]logs.go:105 func2() DEBUG : Local file system at /www/wwwroot/rec.qiuye.ink/rec/down/usadapekora: Making directory  src=rclone
5|vtb_rec  | INFO[0300]downloader.go:23 DownloadVideo() start to download                             title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"
5|vtb_rec  | INFO[0300]downloadStreamlink.go:38 StartDownload() start to download /www/wwwroot/rec.qiuye.ink/rec/down/usadapekora/【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】_1604417421.ts, command [--http-cookies CONSENT=YES+CN.zh-CN+20180415-11-0; PREF=al=zh-CN&cvdm=grid&f5=30030; SID=2wepOKsSmcdOzWRKaJvSjqNpXr1QSo_roKhClNt4YTtGBJYkuzkL4WoN-h35e49c1UwK3w.; APISID=-upO2_DL3eFweiEM/ACgHhDSXFgwDElLIA; SAPISID=-UaFfiqJfOzDBKPY/Akknq5p4r2bt_a_4U; __Secure-3PAPISID=-UaFfiqJfOzDBKPY/Akknq5p4r2bt_a_4U; SIDCC=AJi4QfHzurEH6swEfO2CRWVgnHuJRg87DgCku5KPBhn4k2W7NAmPtgRnVPYG4BKFEn3n4qSgtXI https://www.youtube.com/watch?v=QKlL_KGlHHA best]  title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"
5|vtb_rec  | WARN[0300]downloadStreamlink.go:79 func2() Error during writing streamlink video         error="read |0: file already closed" title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"
5|vtb_rec  | INFO[0300]downloader.go:26 DownloadVideo() finished with status: read |0: file already closed  title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"
5|vtb_rec  | INFO[0300]downloader.go:31 DownloadVideo() /www/wwwroot/rec.qiuye.ink/rec/down/usadapekora/【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】_1604417421.ts download successfully  title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"
5|vtb_rec  | INFO[0300]videoProcesser.go:200 keepLiveAlive() Got emergency triggerChan signal, refresh at once!  title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"
5|vtb_rec  | INFO[0300]logs.go:105 func2() DEBUG : 【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】_1604417421.ts: Size and modification time the same (differ by 0s, within tolerance 1ns)  src=rclone
5|vtb_rec  | INFO[0300]downloader.go:23 DownloadVideo() start to download                             title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"
5|vtb_rec  | INFO[0300]downloadStreamlink.go:38 StartDownload() start to download /www/wwwroot/rec.qiuye.ink/rec/down/usadapekora/【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】_1604417421.ts, command [--http-cookies CONSENT=YES+CN.zh-CN+20180415-11-0; PREF=al=zh-CN&cvdm=grid&f5=30030; SID=2wepOKsSmcdOzWRKaJvSjqNpXr1QSo_roKhClNt4YTtGBJYkuzkL4WoN-h35e49c1UwK3w.; APISID=-upO2_DL3eFweiEM/ACgHhDSXFgwDElLIA; SAPISID=-UaFfiqJfOzDBKPY/Akknq5p4r2bt_a_4U; __Secure-3PAPISID=-UaFfiqJfOzDBKPY/Akknq5p4r2bt_a_4U; SIDCC=AJi4QfHzurEH6swEfO2CRWVgnHuJRg87DgCku5KPBhn4k2W7NAmPtgRnVPYG4BKFEn3n4qSgtXI https://www.youtube.com/watch?v=QKlL_KGlHHA best]  title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"
5|vtb_rec  | WARN[0300]downloadStreamlink.go:79 func2() Error during writing streamlink video         error="read |0: file already closed" title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"
5|vtb_rec  | INFO[0300]downloader.go:26 DownloadVideo() finished with status: read |0: file already closed  title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"
5|vtb_rec  | INFO[0300]downloader.go:31 DownloadVideo() /www/wwwroot/rec.qiuye.ink/rec/down/usadapekora/【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】_1604417421.ts download successfully  title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"
5|vtb_rec  | INFO[0300]logs.go:105 func2() DEBUG : 【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】_1604417421.ts: Size and modification time the same (differ by 0s, within tolerance 1ns)  src=rclone
5|vtb_rec  | INFO[0301]videoProcesser.go:225 isNewLive() [isNewLive] live offline                      title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"
5|vtb_rec  | INFO[0301]videoProcesser.go:177 startDownloadVideo() Do postprocessing...                          title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"
5|vtb_rec  | INFO[0301]logs.go:105 func2() DEBUG : Local file system at /www/wwwroot/rec.qiuye.ink/rec/up: Making directory  src=rclone
5|vtb_rec  | INFO[0301]shellSupport.go:41 func2() ffmpeg version 3.4.8-0ubuntu0.2 Copyright (c) 2000-2020 the FFmpeg developers  title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"
5|vtb_rec  | INFO[0301]shellSupport.go:41 func2()   built with gcc 7 (Ubuntu 7.5.0-3ubuntu1~18.04)  title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"
5|vtb_rec  | INFO[0301]shellSupport.go:41 func2()   configuration: --prefix=/usr --extra-version=0ubuntu0.2 --toolchain=hardened --libdir=/usr/lib/x86_64-linux-gnu --incdir=/usr/include/x86_64-linux-gnu --enable-gpl --disable-stripping --enable-avresample --enable-avisynth --enable-gnutls --enable-ladspa --enable-libass --enable-libbluray --enable-libbs2b --enable-libcaca --enable-libcdio --enable-libflite --enable-libfontconfig --enable-libfreetype --enable-libfribidi --enable-libgme --enable-libgsm --enable-libmp3lame --enable-libmysofa --enable-libopenjpeg --enable-libopenmpt --enable-libopus --enable-libpulse --enable-librubberband --enable-librsvg --enable-libshine --enable-libsnappy --enable-libsoxr --enable-libspeex --enable-libssh --enable-libtheora --enable-libtwolame --enable-libvorbis --enable-libvpx --enable-libwavpack --enable-libwebp --enable-libx265 --enable-libxml2 --enable-libxvid --enable-libzmq --enable-libzvbi --enable-omx --enable-openal --enable-opengl --enable-sdl2 --enable-libdc1394 --enable-libdrm --enable-libiec61883 --enable-chromaprint --enable-frei0r --enable-libopencv --enable-libx264 --enable-shared  title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"
5|vtb_rec  | INFO[0301]shellSupport.go:41 func2()   libavutil      55. 78.100 / 55. 78.100      title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"
5|vtb_rec  | INFO[0301]shellSupport.go:41 func2()   libavcodec     57.107.100 / 57.107.100      title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"
5|vtb_rec  | INFO[0301]shellSupport.go:41 func2()   libavformat    57. 83.100 / 57. 83.100      title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"
5|vtb_rec  | INFO[0301]shellSupport.go:41 func2()   libavdevice    57. 10.100 / 57. 10.100      title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"
5|vtb_rec  | INFO[0301]shellSupport.go:41 func2()   libavfilter     6.107.100 /  6.107.100      title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"
5|vtb_rec  | INFO[0301]shellSupport.go:41 func2()   libavresample   3.  7.  0 /  3.  7.  0      title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"
5|vtb_rec  | INFO[0301]shellSupport.go:41 func2()   libswscale      4.  8.100 /  4.  8.100      title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"
5|vtb_rec  | INFO[0301]shellSupport.go:41 func2()   libswresample   2.  9.100 /  2.  9.100      title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"
5|vtb_rec  | INFO[0301]shellSupport.go:41 func2()   libpostproc    54.  7.100 / 54.  7.100      title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"
5|vtb_rec  | INFO[0301]shellSupport.go:41 func2() concat:/www/wwwroot/rec.qiuye.ink/rec/down/usadapekora/【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】_1604417421.ts|/www/wwwroot/rec.qiuye.ink/rec/down/usadapekora/【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】_1604417421.ts|: Invalid data found when processing input  title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"
5|vtb_rec  | WARN[0301]videoProcesser.go:331 mergeVideo() /www/wwwroot/rec.qiuye.ink/rec/up/usadapekora/【2020-11-03】【23:30:21】【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】_merged_1604417422.mp4 the video file don't exist  title="【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】" user="Youtube|usadapekora"`
程序生成的log
`
{"file":"/home/runner/work/Vtb_Record/Vtb_Record/config/prof.go:84","func":"github.com/fzxiao233/Vtb_Record/config.InitProfiling","level":"debug","msg":"scvg use 4.327584ms","prof":true,"time":"2020-11-03T23:25:32+08:00"}
{"file":"/home/runner/work/Vtb_Record/Vtb_Record/live/videoworker/downloader/provbase/downloader.go:23","func":"github.com/fzxiao233/Vtb_Record/live/videoworker/downloader/provbase.(*Downloader).DownloadVideo","level":"info","msg":"start to download","time":"2020-11-03T23:25:34+08:00","title":"【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】","user":"Youtube|usadapekora"}
{"file":"/home/runner/work/Vtb_Record/Vtb_Record/live/videoworker/downloader/provstreamlink/downloadStreamlink.go:38","func":"github.com/fzxiao233/Vtb_Record/live/videoworker/downloader/provstreamlink.(*DownloaderStreamlink).StartDownload","level":"info","msg":"start to download /www/wwwroot/rec.qiuye.ink/rec/down/usadapekora/【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】_1604417134.ts, command [--http-cookies CONSENT=YES+CN.zh-CN+20180415-11-0; PREF=al=zh-CN\u0026cvdm=grid\u0026f5=30030; SID=2wepOKsSmcdOzWRKaJvSjqNpXr1QSo_roKhClNt4YTtGBJYkuzkL4WoN-h35e49c1UwK3w.; APISID=-upO2_DL3eFweiEM/ACgHhDSXFgwDElLIA; SAPISID=-UaFfiqJfOzDBKPY/Akknq5p4r2bt_a_4U; __Secure-3PAPISID=-UaFfiqJfOzDBKPY/Akknq5p4r2bt_a_4U; SIDCC=AJi4QfHzurEH6swEfO2CRWVgnHuJRg87DgCku5KPBhn4k2W7NAmPtgRnVPYG4BKFEn3n4qSgtXI https://www.youtube.com/watch?v=QKlL_KGlHHA best]","time":"2020-11-03T23:25:34+08:00","title":"【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】","user":"Youtube|usadapekora"}
{"error":"read |0: file already closed","file":"/home/runner/work/Vtb_Record/Vtb_Record/live/videoworker/downloader/provstreamlink/downloadStreamlink.go:79","func":"github.com/fzxiao233/Vtb_Record/live/videoworker/downloader/provstreamlink.(*StreamlinkDownload).doDownload.func2","level":"warning","msg":"Error during writing streamlink video","time":"2020-11-03T23:25:34+08:00","title":"【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】","user":"Youtube|usadapekora"}
{"file":"/home/runner/work/Vtb_Record/Vtb_Record/live/videoworker/downloader/provbase/downloader.go:26","func":"github.com/fzxiao233/Vtb_Record/live/videoworker/downloader/provbase.(*Downloader).DownloadVideo","level":"info","msg":"finished with status: read |0: file already closed","time":"2020-11-03T23:25:34+08:00","title":"【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】","user":"Youtube|usadapekora"}
{"file":"/home/runner/work/Vtb_Record/Vtb_Record/live/videoworker/downloader/provbase/downloader.go:28","func":"github.com/fzxiao233/Vtb_Record/live/videoworker/downloader/provbase.(*Downloader).DownloadVideo","level":"info","msg":"/www/wwwroot/rec.qiuye.ink/rec/down/usadapekora/【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】_1604417134.ts the video file don't exist","time":"2020-11-03T23:25:34+08:00","title":"【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】","user":"Youtube|usadapekora"}
{"file":"/home/runner/work/Vtb_Record/Vtb_Record/live/videoworker/videoProcesser.go:156","func":"github.com/fzxiao233/Vtb_Record/live/videoworker.(*ProcessVideo).startDownloadVideo.func1","level":"info","msg":"Failed to record, trying to refresh live state!","time":"2020-11-03T23:25:34+08:00","title":"【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】","user":"Youtube|usadapekora"}
{"file":"/home/runner/work/Vtb_Record/Vtb_Record/live/videoworker/videoProcesser.go:160","func":"github.com/fzxiao233/Vtb_Record/live/videoworker.(*ProcessVideo).startDownloadVideo.func1","level":"info","msg":"Waiting for next refresh before we retry","time":"2020-11-03T23:25:34+08:00","title":"【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】","user":"Youtube|usadapekora"}
{"file":"/home/runner/work/Vtb_Record/Vtb_Record/config/logs.go:105","func":"github.com/fzxiao233/Vtb_Record/config.InitLog.func2","level":"info","msg":"DEBUG : 【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】_1604417134.ts: Size and modification time the same (differ by 0s, within tolerance 1ns)","src":"rclone","time":"2020-11-03T23:25:34+08:00"}
{"file":"/home/runner/work/Vtb_Record/Vtb_Record/live/videoworker/videoProcesser.go:200","func":"github.com/fzxiao233/Vtb_Record/live/videoworker.(*ProcessVideo).keepLiveAlive","level":"info","msg":"Got emergency triggerChan signal, refresh at once!","time":"2020-11-03T23:25:34+08:00","title":"【Minecraft】みんなでエンドシティを探索ぺこ！【ホロライブ#兎田ぺこら】","user":"Youtube|usadapekora"}
{"file":"/home/runner/work/Vtb_Record/Vtb_Record/config/prof.go:84","func":"github.com/fzxiao233/Vtb_Record/config.InitProfiling","level":"debug","msg":"scvg use 6.325907ms","prof":true,"time":"2020-11-03T23:25:35+08:00"}
{"file":"/home/runner/work/Vtb_Record/Vtb_Record/config/prof.go:84","func":"github.com/fzxiao233/Vtb_Record/config.InitProfiling","level":"debug","msg":"scvg use 4.378513ms","prof":true,"time":"2020-11-03T23:25:38+08:00"}
`

**Comment by fzxiao233** [comment]
ffmpeg合并的神秘问题还是有点多的...
我再排查下吧，这个光看日志我也不知道是什么发生的...

**Comment by kksula** [comment]
不好意思，借串詢問
win10環境
出現
![1610090179420](https://user-images.githubusercontent.com/77254343/104141542-446b3600-53f2-11eb-8b10-d15b5b0bdf50.jpg)
請問我該如何排除
另外就是該如何關閉程式 似乎在工作管理員找不到

**Comment by fzxiao233** [comment]
> 不好意思，借串詢問
> win10環境
> 出現
> ![qk7ffu5](https://user-images.githubusercontent.com/77254343/104141614-a5930980-53f2-11eb-94c6-e0f0b4ac9990.png)
> 
> 請問我該如何排除
> 另外就是該如何關閉程式 似乎在工作管理員找不到

您好，请安装一下 streamlink 呢，按下ctrl + c 可以关闭程序

**Comment by kksula** [comment]
有安裝Streamlink了說 還是我安裝的姿勢不對?

![image](https://user-images.githubusercontent.com/77254343/104325350-80ea7f00-5523-11eb-8292-ce6fe833d8f3.png)
![image](https://user-images.githubusercontent.com/77254343/104325393-93fd4f00-5523-11eb-818c-bf5a73fdc660.png)

**Comment by Yang-Xijie** [comment]
Error during writing streamlink video error="read |0: file already closed"

我也遇到了这个问题，macOS 11.2

**Comment by fzxiao233** [comment]
更新即可解决
