### ISSUE TITLE
请问有提供Docker版的计划吗？

### ISSUE THREAD

**Issue by Aragamiz** [fzxiao233/Vtb_Record#76]
Docker版更适合低功耗NAS一些，平衡一下录播存储成本。

**Comment by fzxiao233** [comment]
诶，NAS没有直接的 Linux 环境吗？
这只是个单文件程序，貌似放进 docker 没有什么意义

**Comment by Aragamiz** [comment]
> 诶，NAS没有直接的 Linux 环境吗？
> 这只是个单文件程序，貌似放进 docker 没有什么意义

有呀，docker也有Ubuntu，但对于大众atom的nas来说跑起来太费劲了，虚拟机也是。我已经放弃了去用VPS了。
但毕竟docker还是可以跑跑百度云的，录播机应该也行吧。
还有就是docker在Nas系统上很易用，可以很简单的挂载Nas本地储存和映射本地端口，组起录播机来成本很低也很简单的。
