### ISSUE TITLE
报错： Init config! config file error: While parsing config: invalid character '/' looking for beginning of object key string

### ISSUE THREAD

**Issue by Uc207Pr4f57t9-251** [fzxiao233/Vtb_Record#80]
**版本0.5.0**
**windows**
**已经安装了streamlink、ffmpeg**
用github上给的config贴进去改了相关的参数：

{
  "EnableProxy": false,  // 是否启用代理
  "Proxy": "127.0.0.1:10800",  //代理地址，应为socks5代理
  "RedisHost": "127.0.0.1:6379",  //Redis数据库地址 用于启用上传功能，不使用无需配置
  "CriticalCheckSec": 30, // 检测间隔
  "NormalCheckSec": 30, // 检测间隔
  "ExpressPort": 3000,  // 配置同传获取服务器的端口，详细见后文
  "DownloadQuality": "best",  // 配置下载画质 best为最佳画质 建议不调整 可选: best 1080p60 720p
  "DownloadDir": "I:\vtbrec",  // 下载目录 注意后无斜杠
  "EnableTS2MP4": true,  // 是否启用ts转码mp4（关闭后断流文件不会合并
  "Module": [
    {
      "Name": "Youtube",  // 模块名，以下类推
      "Enable": true,  // 是否启用该模块
      "Users": [  // 监测对象配置，详细见下文
        {
          "TargetId": "UC2wKfjlioOCLP4xQMOWNcgg",
          "Name": "test",
          "NeedDownload": true,
          "NeedCQBot": false,
          "CQHost": "",
          "CQToken": "",
          "QQGroupID": [
            ""
          ],
        }
      ]
      "HttpHeaders": {
        "Cookie": "VISITOR_INFO1_LIVE=WCtZX6GLxQA; CONSENT=YES+CN.en+20171217-09-0; SID=3wfzVrbE28STne3AowYS7whtmlt5nFudl7R76BgxSCjg0XBkzmxTvOUwHzJqMJqcUJwlXQ.; __Secure-3PSID=3wfzVrbE28STne3AowYS7whtmlt5nFudl7R76BgxSCjg0XBkrno2Pjh8AWjbiZIHyoP2dg.; HSID=AFvShIsEFW81y0RMa; SSID=AXgklfCyimlEcLnTX; APISID=r_bTJXh6sgOnDYNp/AA1T38yRW3PoK3rGy; SAPISID=wvWEg4ZA5YvnDFm1/AIbvpUUlVzBlmQsKz; __Secure-3PAPISID=wvWEg4ZA5YvnDFm1/AIbvpUUlVzBlmQsKz; LOGIN_INFO=AFmmF2swRQIgMrmACWNuiVsVS1GSkFzQVBjX1Q1d2pQTjN0dm41LWZxekZLZWExS1prSklLaEI3VDM1S05kSVMwU1JEU1dZWjFiMDJDQWswMXJrOW93; PREF=f6=40000000&al=en&f4=4000000&f5=30000; YSC=xh7k8gFO0B0; SIDCC=AJi4QfHZZMBy3C_KVneCcfwkO13AkInMlFClhJRFu6ewMjb9ug8-CCc9-4tXowJNBfkr-z2_WQ; __Secure-3PSIDCC=AJi4QfEDcgBamb5nOd07rFULojMNX2VwoqWl_924PogCUjkGt6hCJvEXlZRq7PLv9MlZ7oC-jQ"
      }
    },
    {
      "Name": "Twitcasting",
      "Enable": false,
      "Users": [
        {
          "TargetId": "natsuiromatsuri",
          "Name": "natsuiromatsuri",
          "NeedDownload": true,
          "NeedCQBot": true,
          "CQHost": "",
          "CQToken": "",
          "QQGroupID": [],
          "TransBiliId": "336731767"
        }
      ]
    },
    {
      "Name": "Bilibili",
      "Enable": false,
      "Users": [
        {
          "TargetId": "336731767",
          "Name": "natsuiromatsuri",
          "NeedDownload": false,
          "NeedCQBot": true,
          "CQHost": "",
          "CQToken": "",
          "QQGroupID": [
          ]
        }
      ]
    }
  ]
}

**Comment by fzxiao233** [comment]
你好，请去掉 config 中的 // 和 // 后的注释内容
建议你修改 config_example.json 为 config.json 并参照文档填写 config
