### ISSUE TITLE
程式小白問個

### ISSUE THREAD

**Issue by kksula** [fzxiao233/Vtb_Record#84]
![image](https://user-images.githubusercontent.com/77254343/113440585-4ce67200-941f-11eb-9d9b-e337b83fa8ef.png)

不好意思想請問一下這個應該是沒有開始正常工作吧 
只想下載並不進行上傳的話
請問我該如何設定?

另外就是下載位置該如何設定?
比如說我這個放C槽 但下載的地方放置H槽
請問我這樣設定是對的嗎?
![image](https://user-images.githubusercontent.com/77254343/113440733-8ae39600-941f-11eb-9ecb-34ff2d6a1aa2.png)

**Comment by fzxiao233** [comment]
你好，您的配置的是对的呢
