### ISSUE TITLE
Twitcasting录制失败

### ISSUE THREAD

**Issue by jkfujr** [fzxiao233/Vtb_Record#90]
配置
`{
  "NormalCheckSec": 30,
  "CriticalCheckSec": 25,
  "DownloadQuality": "best",
  "DownloadDir": "E:\\Cache\\录播\\Vtb_Record",
  "EnableTS2MP4": true,
  "SRT": false,
  "VTT": true,
  "Module": [
    {
      "Name": "Twitcasting",
      "Enable": true,
      "Proxy": "127.0.0.1:10808",
      "DownloadProvider": "streamlink",
      "Users": [
        {
          "TargetId": "kagarin_cas",
          "Name": "TEST",
          "NeedDownload": true
        }
      ]
    }
}`
日志
`INFO[0014]downloader.go:22 DownloadVideo() start to download                             title="kagarin_cas#732211385" user="Twitcasting|TEST"
INFO[0014]downloadStreamlink.go:28 StartDownload() start to download E:\Cache\录播\Vtb_Record/TEST/kagarin_cas#732211385_1652912685.ts, command [--force -o E:\Cache\录播\Vtb_Record/TEST/kagarin_cas#732211385_1652912685.ts https://twitcasting.tv/kagarin_cas best]  title="kagarin_cas#732211385" user="Twitcasting|TEST"
[cli][info] Found matching plugin twitcasting for URL https://twitcasting.tv/kagarin_cas
error: Unable to open URL: https://twitcasting.tv/streamserver.php?target=kagarin_cas&mode=client (HTTPSConnectionPool(host='twitcasting.tv', port=443): Max retries exceeded with url: /streamserver.php?target=kagarin_cas&mode=client (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:1129)'))))
INFO[0015]downloader.go:25 DownloadVideo() finished with status: %!s(<nil>)              title="kagarin_cas#732211385" user="Twitcasting|TEST"
INFO[0015]downloader.go:27 DownloadVideo() download failed: %!s(<nil>)                   title="kagarin_cas#732211385" user="Twitcasting|TEST"
INFO[0015]videoProcesser.go:154 func1() Failed to record, trying to refresh live state!  title="kagarin_cas#732211385" user="Twitcasting|TEST"
INFO[0015]videoProcesser.go:198 keepLiveAlive() Got emergency triggerChan signal, refresh at once!  title="kagarin_cas#732211385" user="Twitcasting|TEST"
INFO[0015]videoProcesser.go:158 func1() Waiting for next refresh before we retry      title="kagarin_cas#732211385" user="Twitcasting|TEST"
`
有解决方法么

**Comment by AlotOfBlahaj** [comment]
tc台把流换成ws推送了，估计streamlink还没更新
